// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASX7x63qKZzshOCZJ05hFABExP0060R9c',
    appId: '1:620658807350:android:9485e7aeb731b14429be97',
    messagingSenderId: '620658807350',
    projectId: 'vitalize-42475',
    storageBucket: 'vitalize-42475.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3evNEMqOW5msRIuQT34HxfHsjnuHtHQU',
    appId: '1:620658807350:ios:0d61658bde4e998e29be97',
    messagingSenderId: '620658807350',
    projectId: 'vitalize-42475',
    storageBucket: 'vitalize-42475.appspot.com',
    iosBundleId: 'com.example.vitalize',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3evNEMqOW5msRIuQT34HxfHsjnuHtHQU',
    appId: '1:620658807350:ios:e3e6b765e84f1d2129be97',
    messagingSenderId: '620658807350',
    projectId: 'vitalize-42475',
    storageBucket: 'vitalize-42475.appspot.com',
    iosBundleId: 'com.example.vitalize.RunnerTests',
  );
}
